context.modules = [
  {
    name = libpipewire-module-rt
    args = {
      nice.level = -20
      rt.prio = 95
      rt.time.soft = -1
      rt.time.hard = -1
    }
    flags = [ ifexists nofail ]
  }
]
