# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Kierownik defaults (but don't edit these directly!)
source = /usr/share/hypr/autostart.conf
source = /usr/share/hypr/bindings.conf
source = /usr/share/hypr/envs.conf
source = /usr/share/hypr/looknfeel.conf
source = /usr/share/hypr/windows.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/hyprland.conf