# Refer to https://wiki.hyprland.org/Configuring/Variables/

# Variables
$activeBorderColor = rgba(33ccffee) rgba(00ff99ee) 45deg
$inactiveBorderColor = rgba(595959aa)

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 2
    gaps_out = 4

    border_size = 0

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = scrolling
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 4
    
    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    dim_inactive = false
    
    shadow {
        enabled = false
    }

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = false
    }
}

# https://wiki.hypr.land/Configuring/Variables/#group
group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
    col.border_locked_active = -1
    col.border_locked_inactive = -1

    groupbar {
        font_size = 12
        font_family = monospace
        font_weight_active = ultraheavy
        font_weight_inactive = normal

        indicator_height = 0
        indicator_gap = 5
        height = 22
        gaps_in = 5
        gaps_out = 0

        text_color = rgb(ffffff)
        text_color_inactive = rgba(ffffff90)
        col.active = rgba(00000040)
        col.inactive = rgba(00000020)

        gradients = true
        gradient_rounding = 0
        gradient_round_only_edges = false
    }
}

scrolling {
    fullscreen_on_one_column = false
    explicit_column_widths = 0.333, 0.5, 0.667, 1.0
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    disable_hyprland_logo = true
    disable_splash_rendering  = true
    disable_hyprland_guiutils_check = true
    focus_on_activate = true
    anr_missed_pings = 3
    on_focus_under_fullscreen = 1
}

# https://wiki.hypr.land/Configuring/Variables/#cursor
cursor {
    hide_on_key_press = true
    warp_on_change_workspace = 1
}

# Auto toggle scratchpad on switching workspace from scratchpad
binds {
    hide_special_on_workspace_change = true
}

# Style Gum confirm to match terminal theme
env = GUM_CONFIRM_PROMPT_FOREGROUND,6       # Cyan
env = GUM_CONFIRM_SELECTED_FOREGROUND,0     # Black
env = GUM_CONFIRM_SELECTED_BACKGROUND,2     # Green
env = GUM_CONFIRM_UNSELECTED_FOREGROUND,7   # White
env = GUM_CONFIRM_UNSELECTED_BACKGROUND,8   # Dark grey
