# Set default authfile location
authfile=/etc/u2f_mappings

# Enable cue prompt to remind users to touch the device
cue
# Set a custom prompt for the cue option
[cue_prompt=Touch your key]

# No user action nor presence required
pinverification=0
userpresence=0
userverification=0

# Debug
# debug
