#!/usr/bin/env bash

#MISE description="Extract ssh pub key with email"
subkey_keygrip=$(gpg --list-keys --with-keygrip | awk '$0 ~ /\[A\]/ {getline; print $3}')

if [[ ! -f "$HOME/.gnupg/sshcontrol" ]]; then
    echo "${subkey_keygrip}" >> "$HOME/.gnupg/sshcontrol"
fi

identity_file="$HOME/.identity"
default_email=""
if [[ -f "$identity_file" ]]; then
    default_email=$(jq -r '.emailAddress' "$identity_file")
fi

user_email=$(gum input --prompt "Enter your email : " --value "$default_email")
ssh_pubkey=$(gpg --export-ssh-key "${user_email}")
gum log --time=false --level info "Your ssh pub key is :"
gum style "${ssh_pubkey}"

gum confirm "Copy to clipboard?" && gpg --export-ssh-key "${user_email}" | wl-copy
