#!/usr/bin/env bash

#MISE description="Extract gpg sign pub key"
set -euo pipefail

gpg_key_id=$(gpg2 --list-secret-keys --keyid-format LONG | grep ssb | grep '[S]' | sed -E 's/.*\/([0-9A-Z]*) .*\[S\]/\1/')
    
gpg_pubkey=$(gpg --armor --export "${gpg_key_id}")
echo "Your gpg pub key is"
echo "${gpg_pubkey}"

gum confirm "Copy to clipboard?" && gpg --armor --export "${gpg_key_id}" | wl-copy
