#!/usr/bin/env bash

#MISE description="Generate gpg keys"
set -euo pipefail

identity_file="$HOME/.identity"
default_name=""
default_email=""
if [[ -f "$identity_file" ]]; then
    default_name=$(jq -r '.realName' "$identity_file")
    default_email=$(jq -r '.emailAddress' "$identity_file")
fi

user_name=$(gum input --prompt "Enter your name : " --value "$default_name")
user_email=$(gum input --prompt "Enter your email : " --value "$default_email")

## Create the master key ( cert ) & sub key [SEA]
gpg2 --batch --gen-key <<EOK
Key-Type: RSA
Key-Length: 4096
Key-Usage: cert
Subkey-Type: RSA
Subkey-Length: 4096
Subkey-Usage: sign
Name-Real: ${user_name}
Name-Email: ${user_email}
Expire-Date: 0
EOK

# Retrieve the key fingerprint
FPR=$(gpg --list-keys --with-colons "${user_email}" 2>/dev/null | awk -F: '/^fpr:/ {print $10; exit}')

# Add an encryption sub-key
gpg --batch --passphrase '' --quick-add-key ${FPR} rsa4096 encrypt 0

# Add an authentication sub-key
gpg --batch --passphrase '' --quick-add-key ${FPR} rsa4096 auth 0

# Save pub key
gpg --output public.key --armor --export "${user_email}"