[tools]
rust = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:blue-build" = "latest"
"opencode" = "latest"

[settings]
windows_default_inline_shell_args = "pwsh -c"

[settings.cargo]
binstall = true

[env]
BASE_IMAGE = 'quay.io/fedora/fedora-bootc:43'
BIB_IMAGE  = 'ghcr.io/osbuild/bootc-image-builder:latest'
ROOTFS     = 'btrfs'

[tasks.build_oci]
usage = '''
arg "target" help="target" {
 choices "base" "wm"
}
'''
run = '''
bluebuild build recipes/recipe-{{ usage.target }}.yml
'''

[tasks.build_iso]
usage = '''
arg "target" help="target" {
 choices "base" "wm"
}
'''
run = '''
bluebuild generate-iso --iso-name kier-{{ usage.target }}.iso recipe recipes/recipe-{{ usage.target }}.yml
'''

[tasks.build_qcow2]
usage = '''
arg "target" help="target" {
 choices "base" "wm"
}
'''
run = '''
mkdir -p /tmp/output

sudo podman pull ghcr.io/lgranie/kierownik-{{ usage.target }}:latest

sudo podman run --rm --privileged --pull=newer \
    --security-opt label=type:unconfined_t \
    -v ./bib/config/qcow2.toml:/config.toml:ro \
    -v ./bib/defs/kierownik-43.yaml:/usr/share/bootc-image-builder/defs/kierownik-43.yaml:ro \
    -v /tmp/output:/output \
    -v /var/lib/containers/storage:/var/lib/containers/storage \
    -v /boot:/boot \
    {{ env.BIB_IMAGE }} \
    --progress term \
    --target-arch amd64 \
    --type qcow2 \
    --rootfs {{ env.ROOTFS }} \
    --installer-payload-ref {{ env.BASE_IMAGE }} \
    ghcr.io/lgranie/kierownik-{{ usage.target }}:latest
'''

[tasks.vm]
usage = '''
arg "target" help="Target environment" {
  choices "base" "wm"
}
'''
run = '''
set -xeuo pipefail

sudo virt-install \
    --name kier-{{ usage.target }} \
    --boot uefi,firmware.feature0.name=secure-boot,firmware.feature0.enabled=no \
    --memory 8192 \
    --vcpus 8 \
    --disk path=/tmp/output/qcow2/disk-{{ usage.target }}.qcow2,size=8 \
    --os-variant fedora41 \
    --network bridge=virbr0 \
    --graphics spice,gl=on \
    --video virtio,accel3d=on \
    --xml './devices/graphics/listen/@type=none' \
    --noautoconsole
'''