#!/usr/bin/env bash
#MISE description="Run image in VM via virt-install"
#USAGE arg "<target>" help="Target environment" { choices "N100" "8745" "5290" }
set -oue pipefail

run0 virt-install \
    --name krw-"${usage_target}" \
    --boot uefi,firmware.feature0.name=secure-boot,firmware.feature0.enabled=no \
    --memory 8192 \
    --vcpus 8 \
    --disk path=/tmp/output/qcow2/disk-"${usage_target}".qcow2,size=8 \
    --os-variant fedora41 \
    --network bridge=virbr0 \
    --graphics spice,gl=on \
    --video virtio,accel3d=on \
    --xml './devices/graphics/listen/@type=none' \
    --noautoconsole
