#!/usr/bin/env bash

#MISE description="Init waydroid"
set -euo pipefail

run0 bash -c 'waydroid init \
    --system_channel https://ota.waydro.id/system \
    --vendor_channel https://ota.waydro.id/vendor'
    