#!/usr/bin/env bash

set -euo pipefail

# Download binary
curl -fsSL https://ollama.com/download/ollama-linux-amd64.tar.zst | tar --zstd -x -C /usr
curl -fsSL https://ollama.com/download/ollama-linux-amd64-rocm.tar.zst | tar --zstd -x -C /usr
chmod +x /usr/bin/ollama

# Create user
useradd -r -s /usr/sbin/nologin -m -d /var/cache/ollama ollama
usermod -aG render,video ollama  # For AMD GPU access
