[tools]
"cargo:blue-build" = "latest"
"cargo:cargo-binstall" = "latest"
"opencode" = "latest"
rust = "latest"

[settings]
windows_default_inline_shell_args = "pwsh -c"

[settings.cargo]
binstall = true

[env]
BASE_IMAGE = 'quay.io/fedora/fedora-bootc:44'
BIB_IMAGE  = 'ghcr.io/osbuild/bootc-image-builder:latest'
ROOTFS     = 'btrfs'
BB_REGISTRY = 'ghcr.io/lgranie'
