[terminal]
vt = 1

[default_session]
command = "tuigreet --remember-session --cmd start-wm-session hyprland"
user = "greetd"

[theme]
border = "magenta"
text = "green"
time = "blue"
container = "black"
title = "cyan"
greet = "yellow"
prompt = "magenta"
input = "white"
action = "bright-blue"
button = "bright-red"