#!/usr/bin/env bash

set -euo pipefail

fetch_gh_latest_tag() {
    local repo="$1"
    curl --silent --retry 3 "https://api.github.com/repos/${repo}/releases/latest" | jq -r '.tag_name // empty' 2>/dev/null || true
}

ZED_RELEASE=$(fetch_gh_latest_tag "zed-industries/zed")
curl --silent --retry 3 -L --output - "https://github.com/zed-industries/zed/releases/download/${ZED_RELEASE}/zed-linux-x86_64.tar.gz" \
    | tar -xzf - -C /usr/lib/opt/

# Link binary
ln -sf /usr/lib/opt/zed.app/bin/zed /usr/bin/zed

# Install .desktop
install -D /usr/lib/opt/zed.app/share/applications/dev.zed.Zed.desktop -t /usr/share/applications
sed -i "s|Icon=zed|Icon=/usr/lib/opt/zed.app/share/icons/hicolor/512x512/apps/zed.png|g" /usr/share/applications/dev.zed.Zed.desktop
sed -i "s|Exec=zed|Exec=/usr/lib/opt/zed.app/bin/zed|g" /usr/share/applications/dev.zed.Zed.desktop
